# Generated by Django 5.0.1 on 2024-04-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Activities',
        ),
        migrations.RenameModel(
            old_name='Flight',
            new_name='Flights',
        ),
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Hotels',
        ),
    ]
